import { Injectable, OnApplicationBootstrap } from '@nestjs/common';
import { AsocomunalService } from '../asocomunal/fachadaService/asocomunal.service';

@Injectable()
export class AsocomunalSeed {
  constructor(private readonly asocomunalService: AsocomunalService) { }

  async seed() {
    const asocomunales = [
      {
        nombre: 'Asocomunal Almaguer',
        municipioId: 1,
        estado: true,
        presidente: 'Carlos Hoyos Ruano',
        telefono: '3208932387',
        correo: 'asociacioncomunalalmaguer@gmail.com',
      },
      {
        nombre: 'Asocomunal Argelia Cabecera',
        municipioId: 2,
        estado: true,
        presidente: 'Eyder Muñoz Rosero',
        telefono: '3117115155',
        correo: 'asocomunalargelia74@gmail.com',
      },
      {
        nombre: 'Asocomunal Cgtos. El Plateado la Emboscada y S.',
        municipioId: 2,
        estado: true,
        presidente: 'Eliver Arboleda Bermudez',
        telefono: '3187421622',
        correo: 'promotoriargeliacauca@gmail.com;promotoriadejuntas@argelia-cauca.gov.co',
      },
      {
        nombre: 'Asocomunal Balboa',
        municipioId: 3,
        estado: true,
        presidente: 'Andres Felipe Suarez Dorado',
        telefono: '3106153184',
        correo: 'asocomunalbalboa@gmail.com',
      },
      {
        nombre: 'Asocomunal Bolivar',
        municipioId: 4,
        estado: true,
        presidente: 'Fredy Yobany Zemanate',
        telefono: '3122871156',
        correo: 'asocomunalbolivarc@hotmail.com',
      },
      {
        nombre: 'Asocomunal Buenos Aires',
        municipioId: 5,
        estado: true,
        presidente: 'Manuel Cortes Salinas',
        telefono: '3146436320',
        correo: 'asocomunalbuenosaires2225@gmail.com',
      },
      {
        nombre: 'Asocomunal Alto Naya',
        municipioId: 5,
        estado: true,
        presidente: 'Manuel Tenorio Yonda',
        telefono: '3027830505;3153933757',
        correo: 'desarrollocomunitario@buenosaires-cauca.gov.co;greysigomez1986@gmail.com',
      },
      {
        nombre: 'Asocomunal Cajibio',
        municipioId: 6,
        estado: true,
        presidente: 'Margarett Garcia Guardo',
        telefono: '3137486215',
        correo: 'asocomunalcajibio@gmail.com',
      },
      {
        nombre: 'Asocomunal Caldono',
        municipioId: 7,
        estado: true,
        presidente: 'Silvio Bomba Campo',
        telefono: '3104337775',
        correo: 'asocomunalcaldonocauca@gmail.com',
      },
      {
        nombre: 'Asocomunal Caloto',
        municipioId: 8,
        estado: true,
        presidente: 'Oswaldo Velasco Daza',
        telefono: '3216455133',
        correo: 'asoc.caloto@hotmail.com',
      },
      {
        nombre: 'Asocomunal Corinto',
        municipioId: 9,
        estado: true,
        presidente: 'Vilma Lorena Motta',
        telefono: '3148856543',
        correo: 'jacasocomunalcorinto@gmail.com',
      },
      {
        nombre: 'Asocomunal El Tambo',
        municipioId: 10,
        estado: true,
        presidente: 'Jesus Antonio Caicedo',
        telefono: '3126004342',
        correo: 'asocomunaleltambocauca@gmail.com',
      },
      {
        nombre: 'Asocomunal Florencia',
        municipioId: 11,
        estado: false,
        presidente: 'No Eligio',
        telefono: null,
        correo: null,
      },
      {
        nombre: 'Asocomunal Guachene',
        municipioId: 12,
        estado: true,
        presidente: 'Oscar Cantoñi Mina',
        telefono: '3207092039',
        correo: 'asocomunalg@gmail.com',
      },
      {
        nombre: 'Asocomunal Guapi',
        municipioId: 13,
        estado: true,
        presidente: 'Daniel Solís Sinisterra',
        telefono: '3136088967',
        correo: 'asocomunalguapi@gmail.com',
      },
      {
        nombre: 'Asocomunal Inza',
        municipioId: 14,
        estado: true,
        presidente: 'Astrid Sanchez Campos',
        telefono: '3133150133',
        correo: 'asocomunalinzacauca@gmail.com',
      },
      {
        nombre: 'Asocomunal Jambalo',
        municipioId: 15,
        estado: true,
        presidente: 'Brandon Velasco Valencia',
        telefono: '3206838330',
        correo: 'asocomunal.jambalo@gmail.com',
      },
      {
        nombre: 'Asocomunal La Sierra',
        municipioId: 16,
        estado: true,
        presidente: 'Heriberto López Albán',
        telefono: '3113538554',
        correo: 'asocomunallasierra@gmail.com',
      },
      {
        nombre: 'Asocomunal La Vega',
        municipioId: 17,
        estado: true,
        presidente: 'Mancer Gerardo Muñoz',
        telefono: '3175584072',
        correo: 'asocomunallavega@gmail.com',
      },
      {
        nombre: 'Asocomunal López de Micay',
        municipioId: 18,
        estado: false,
        presidente: 'No Eligio',
        telefono: null,
        correo: null,
      },
      {
        nombre: 'Asocomunal Mercaderes',
        municipioId: 19,
        estado: true,
        presidente: 'Enrique Aldivar Angulo Velasco',
        telefono: '3207402971',
        correo: 'asocomunal.mercaderes2022@gmail.com',
      },
      {
        nombre: 'Asocomunal Miranda',
        municipioId: 20,
        estado: true,
        presidente: 'Martha Cecilia Valencia Cabezas',
        telefono: '3117965806',
        correo: 'asocomunaldemirada@gmail.com',
      },
      {
        nombre: 'Asocomunal Morales',
        municipioId: 21,
        estado: true,
        presidente: 'Luis Eduardo Valencia Vergara',
        telefono: '3103734753',
        correo: 'desarrollocomunitario@morales-cauca.gov.co',
      },
      {
        nombre: 'Asocomunal Padilla',
        municipioId: 22,
        estado: false,
        presidente: null,
        telefono: null,
        correo: null,
      },
      {
        nombre: 'Asocomunal Paez',
        municipioId: 23,
        estado: true,
        presidente: 'Celestino Ortiz Mera',
        telefono: '3113789142',
        correo: 'asocomunalpaezcauca@hotmail.com',
      },
      {
        nombre: 'Asocomunal Patia',
        municipioId: 24,
        estado: true,
        presidente: 'Maria del Pilar Lopez Herrera',
        telefono: '3127888725',
        correo: 'secretariaasojuntaspatia@gmail.com;presidenciaasojuntas@gmail.com',
      },
      {
        nombre: 'Asocomunal Piamonte',
        municipioId: 25,
        estado: true,
        presidente: 'Gildardo Pastrana',
        telefono: '3115324001',
        correo: 'asocomunalpiamonte@gmail.com',
      },
      {
        nombre: 'Asocomunal Piendamo',
        municipioId: 26,
        estado: true,
        presidente: 'Jose Aymer Mosquera Ramirez',
        telefono: '3113293768',
        correo: 'piendamoasocomunal@gmail.com',
      },
      {
        nombre: 'Asocomunal Popayan',
        municipioId: 27,
        estado: true,
        presidente: 'Jhonatan Constain',
        telefono: '3122639348',
        correo: 'asocomunalpopayancauca@gmail.com',
      },
      {
        nombre: 'Asocomunal Puerto Tejada',
        municipioId: 28,
        estado: true,
        presidente: 'Carlos Arturo Lasso Vasquez',
        telefono: '3184212320',
        correo: 'ptotejadaasojuntas@gmail.com',
      },
      {
        nombre: 'Asocomunal Purace',
        municipioId: 29,
        estado: true,
        presidente: 'Oscar Joel Cuchumbe Chantre',
        telefono: '3216410316',
        correo: 'juntaspurace@gmail.com',
      },
      {
        nombre: 'Asocomunal Rosas',
        municipioId: 30,
        estado: true,
        presidente: 'Eduardo Narvaez',
        telefono: '3216410316',
        correo: 'asocomunalrosas@gmail.com;asocomunalrosascauca2023@hotmail.com',
      },
      {
        nombre: 'Asocomunal San Sebastian',
        municipioId: 31,
        estado: true,
        presidente: 'Felio Roldan Timana Anacona',
        telefono: '3206995085',
        correo: 'contador1@caminosdeoportunidades.com.co;jesusarbeym2@hotmail.com',
      },
      {
        nombre: 'Asocomunal Santa Rosa Cabecera',
        municipioId: 32,
        estado: true,
        presidente: 'Nelson Joaqui',
        telefono: '3148570441',
        correo: 'asojuntassantarosacabecera25@gmail.com',
      },
      {
        nombre: 'Asocomunal Santa Rosa Media Bota',
        municipioId: 32,
        estado: true,
        presidente: 'Edelmo Calvahce',
        telefono: '3212476240',
        correo: 'asojuntassantarosacabecera25@gmail.com',
      },
      {
        nombre: 'Asocomunal Santa Rosa Villalobos',
        municipioId: 32,
        estado: true,
        presidente: 'Alejandro Piamba Jimenez',
        telefono: '3213418027',
        correo: 'asojuntasvillaloboscauca@gmail.com',
      },
      {
        nombre: 'Asocomunal Santander de Quilichao',
        municipioId: 33,
        estado: true,
        presidente: 'Jessica Lasso Choco',
        telefono: '3113643059',
        correo: 'asocomunalquilichao@gmail.com',
      },
      {
        nombre: 'Asocomunal Silvia',
        municipioId: 34,
        estado: true,
        presidente: 'Wilson Ferney Chilo Pito',
        telefono: '3216413372',
        correo: 'asocomunalsilviacauca@gmail.com',
      },
      {
        nombre: 'Asocomunal Sotara',
        municipioId: 35,
        estado: true,
        presidente: 'Vilma Yamileth Astaiza Rivera',
        telefono: '3184512686',
        correo: 'sotaraasociaciondejuntas@gmail.com',
      },
      {
        nombre: 'Asocomunal Suarez',
        municipioId: 36,
        estado: true,
        presidente: 'Gersain Soscue Zambrano',
        telefono: '3174914030',
        correo: 'asojuntassuarez@gmail.com',
      },
      {
        nombre: 'Asocomunal Sucre',
        municipioId: 37,
        estado: true,
        presidente: 'Lorena Carvajal Martinez',
        telefono: '3108218229',
        correo: 'asocomunalsucre2023@gmail.com',
      },
      {
        nombre: 'Asocomunal Timbio',
        municipioId: 38,
        estado: true,
        presidente: 'Alfonso Truque Diaz',
        telefono: '3127029949',
        correo: 'asocomunal.timbiocauca@gmail.com',
      },
      {
        nombre: 'Asocomunal Timbiqui',
        municipioId: 39,
        estado: false,
        presidente: 'No Eligio',
        telefono: null,
        correo: null,
      },
      {
        nombre: 'Asocomunal Toribio',
        municipioId: 40,
        estado: true,
        presidente: 'Lirio Velez Noscue Mijera',
        telefono: '3207441313',
        correo: 'asociacionjactoribio@gmail.com',
      },
      {
        nombre: 'Asocomunal Totoro',
        municipioId: 41,
        estado: true,
        presidente: 'Marleny Estela Ibarra M.',
        telefono: '3114831001',
        correo: 'asocomunaltotoro2026@outlook.com',
      },
      {
        nombre: 'Asocomunal Villa Rica',
        municipioId: 42,
        estado: true,
        presidente: 'Jhoan A. Montes Usme',
        telefono: '3216134066',
        correo: 'asocomunalvillarica@hotmail.com',
      },
    ];
    let count = 0;

    for (const a of asocomunales) {
      try {
        await this.asocomunalService.create(a);
        count++;
      } catch (error) {
        console.log(`Error con ${a.nombre}: ${error.message}`);
      }
    }

    console.log(`${count} asocomunales creadas`);
  }
}
